### ISSUE TITLE
question regarding gitea release usage of valuesFrom secret

### ISSUE THREAD

**Issue by jakeschurch** [angelnu/k8s-gitops#2234]
hey @angelnu 

great job on the cluster - i'm going for a similar setup to your [gitea release](https://github.com/angelnu/k8s-gitops/blob/main/apps/default/gitea/release.yaml) I see that value for `gitea.config.database.PASSWD` is defined in  the corresponding secret.yaml -- how are you defining this / doing anything special? Sorry for asking you this - i haven't found similar use in flux docs / other articles / repos 

I define the db password as the following, do you define yours as similar? This would be a big help in moving forward with sops setup - ty!

```
    gitea.yaml: |
        gitea:
            config:
                database:
                    PASSWD: PASSWD

```
